apiVersion: v1
kind: Service
metadata:
  name: llama7b-svc
{{- include "local-llm-stack.labels" . | nindent 2 }}
spec:
  selector:
    app: llama7b
  ports:
  - protocol: TCP
    port: {{ .Values.llama7b.port }}
    targetPort: llama7b-port
  type: ClusterIP
