apiVersion: v1
kind: Service
metadata:
  name: llama13b-svc
{{- include "local-llm-stack.labels" . | nindent 2 }}
spec:
  selector:
    app: llama13b
  ports:
  - protocol: TCP
    port: {{ .Values.llama13b.port }}
    targetPort: llama13b-port
  type: ClusterIP
