apiVersion: v1
kind: Service
metadata:
  name: file-io-svc
{{- include "local-llm-stack.labels" . | nindent 2 }}
spec:
  selector:
    app: file-io-fastapi
  ports:
  - protocol: TCP
    port: {{ .Values.fileio.port }}
    targetPort: file-io-port
  type: ClusterIP
