apiVersion: v1
kind: Service
metadata:
  name: ollama-deepseek-svc
{{- include "local-llm-stack.labels" . | nindent 2 }}
spec:
  selector:
    app: ollama-deepseek
  ports:
  - protocol: TCP
    port: {{ .Values.deepseek.port }}
    targetPort: ollama-port
  type: ClusterIP
