apiVersion: v1
kind: Service
metadata:
  name: ollama-webui-svc
{{- include "local-llm-stack.labels" . | nindent 2 }}
spec:
  selector:
    app: ollama-webui
  ports:
  - protocol: TCP
    port: {{ .Values.webui.port }}
    targetPort: webui-port
  type: ClusterIP
